#!/bin/bash

file="junk"
file2="junk2"
file3="smallsh"

if [ -f "$file" ] ; then
    rm "$file"
fi

if [ -f "$file2" ] ; then
    rm "$file2"
fi

if [ -f "$file3" ] ; then
    rm "$file3"
fi

echo
echo Removed Files
echo